### PR TITLE
moved over a new test file also made additions for replacing how id's…

### PR DESCRIPTION
**Pull request by samrocksc**
#### What's this PR do?

This PR fixes the ID issue mentioned in #19 
#### What are the important parts of the code?

Mainly the constructor, we used the same logic for the random id
#### How should this be tested by the reviewer?

I also pushed up a change to the index.js that gives a 2500ms re-render cycle
#### Is any other information necessary to understand this?

Not really....
#### What are the relevant tickets? (Please add `closes`, `refs`, etc)
#19 , the id's are now placed at the constructor level instead of the render level

### CODE REVIEW

**Comment by phated** [comment]
This seems to include example code for Menus (dropdown) for some reason

**Comment by samrocksc** [comment]
Fixed the dropdown section, I had started working on dropdowns and forgot to remove the  shell.

**Comment by phated** [comment]
This PR looks pretty good (could probably do a little cleanup) but I'm waiting to merge this until the TextField PR is merged.

**Comment by samrocksc** [comment]
I was actually going to recommend before we push a version to do a quick cleanup.

**Comment by samrocksc** [comment]
Made changes to all switchable elements so that the id is now defaulted better.

**Pull request merged**
